### ISSUE TITLE
Grimoire

### ISSUE THREAD

**Issue by maddijoyce** [ephe/ephe.github.com#1]
Hi @ephe,

I noticed your grimoire got DMCA'd, but I really liked using it for my D&D games. Any chance you could zip the files and send it to me. I'd really appreciate it.

If you'd rather not, would you mind telling me how you collated the information. Did you scrape it from a website, or input it all directly.

Thanks for your time,
Maddi

**Comment by kochecc2** [comment]
@ephe what @maddijoyce said

**Comment by ephe** [comment]
Hi! I'm glad that you liked the grimoire! Unfortunately, to comply with the DMCA, I can only distribute the framework, not the spells themselves. I started by typing the spells in manually but made it open to others to contribute/correct spells and basically crowdsourced most of the entry process that way.
